name: Kotlin-CI with Gradle

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

permissions:
  contents: read

jobs:
  build-processor:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build
        run: ./gradlew :processor:build

  publish-package:
    if: github.ref_name == 'main'
    needs: build-processor

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish to GHPR
        run: ./gradlew :processor:publish
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}

