name: Kotlin-CI with Gradle

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

permissions:
  contents: read

jobs:
  build-processor:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Clean
        run: ./gradlew :processor:clean
      - name: Build
        run: ./gradlew :processor:build -x test
      - name: Test
        run: ./gradlew :processor:test

  publish-package:
    needs: build-processor

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish to GHPR
        run: ./gradlew :processor:publish

